### ISSUE TITLE
The results of failed tests are deleted if many tests are run in sequence

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/stf#10]
STF creates a unique directory for each test.  After 10 (by default) directories have been created, the first is deleted before creating the 11th.  This prevents results from using too much disk space (the resutls files may be very large), but retains sufficient history for normal desktop use.
Full regression tests such as test runs within Jenkins build pipelines run many tests in sequence.  If most tests pass but a few fail there is currently a good chance that the results for the failed tests were deleted before the end of the test run, requiring that the test be rerun in isolation to investigate the failure.
If STF had an option to delete the results directory of a test if it passes, then only the failed tests results would exist at the end of the run, which could then be examined without a rerun.

**Comment by adamfarley** [comment]
Sounds like this is complete, after the changes I made. The makefile option to delete the results from passed runs is:

RM_PASS=1
