### ISSUE TITLE
stf looks for tools.jar which does not exist on Java 9

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/stf#3]
openjdk.test.debugging/.classpath contains an entry for tools.jar, which is required if tests are running on java 8.
tools.jar is absent on Java 9 - the classes have been merged into the jdk modules.
stf stops with an exception if any of the classpath entries cannot be found.
Tests still need to run against Java 8, so the classpath entry needs to be present in that situation.
Some code should be added to only resolve a tools.jar entry if we are testing Java 8.

**Comment by lumpfish** [comment]
PR submitted to fix: https://github.com/AdoptOpenJDK/stf/pull/4

**Comment by lumpfish** [comment]
@sxa555, please can you rerun the test with Java 9 and close if OK

**Comment by sxa** [comment]
Looks good. Closing
