### ISSUE TITLE
ant 1.10.1 is not downloadable from the hardcoded link in top.xml

### ISSUE THREAD

**Issue by terryzuoty** [AdoptOpenJDK/stf#31]
**Error message:**

10:53:49 configure-ant-1.10.1:
10:53:49      [echo] Executing macro download-file
10:53:49      [echo] srcurl is http://www-eu.apache.org/dist//ant/binaries/apache-ant-1.10.1-bin.zip
10:53:49      [echo] destdir is /tmp/apache-ant-1.10.1
10:53:49      [echo] destfile is apache-ant-1.10.1-bin.zip
10:53:49      [exec] --2018-02-08 15:53:35--  http://www-eu.apache.org/dist//ant/binaries/apache-ant-1.10.1-bin.zip
10:53:49      [exec] Resolving www-eu.apache.org (www-eu.apache.org)... 195.154.151.36, 2001:bc8:2142:300::
10:53:49      [exec] Connecting to www-eu.apache.org (www-eu.apache.org)|195.154.151.36|:80... connected.
10:53:49      [exec] HTTP request sent, awaiting response... 404 Not Found
10:53:49      [exec] 2018-02-08 15:53:35 ERROR 404: Not Found.
10:53:49      [exec] 
10:53:49      [exec] Result: 8
10:53:49     [unzip] Expanding: /tmp/apache-ant-1.10.1/apache-ant-1.10.1-bin.zip into /home/j9build/workspace/JCK-Java8-OpenJ9-Daily-TKG/openjdk-tests/systemtest_prereqs
10:53:49 
10:53:49 BUILD FAILED
10:53:49 /home/j9build/workspace/JCK-Java8-OpenJ9-Daily-TKG/openjdk-tests/TestConfig/scripts/build_test.xml:149: The following error occurred while executing this line:
10:53:49 /home/j9build/workspace/JCK-Java8-OpenJ9-Daily-TKG/openjdk-tests/jck/build.xml:144: The following error occurred while executing this line:
10:53:49 /home/j9build/workspace/JCK-Java8-OpenJ9-Daily-TKG/openjdk-tests/jck/build.xml:90: The following error occurred while executing this line:
10:53:49 /home/j9build/workspace/JCK-Java8-OpenJ9-Daily-TKG/openjdk-tests/systemtest/stf/stf.build/include/top.xml:143: Error while expanding /tmp/apache-ant-1.10.1/apache-ant-1.10.1-bin.zip

Investigation:

The link `http://www-eu.apache.org/dist//ant/binaries/apache-ant-1.10.1-bin.zip` is not valid anymore and ant start to support 1.10.2 version. I think the hardcoded url is not a good solution which it has to be updated manually everytime ant change it.

There are two ways to avoid this issue:
1. change it to an url which will can provide download this specific version 'permanently'.
2. Or change the url to get the 'latest' version automatically without the need to updating it manually.

**Comment by terryzuoty** [comment]
FYI @Mesbah-Alam

**Comment by Mesbah-Alam** [comment]
Fyi.. @lumpfish : We need to find a way to, preferably, automatically detect the latest version of ant and download it. Otherwise we'd be stuck with having to manually update the Ant URL path everytime they update to a new version.

**Comment by lumpfish** [comment]
The danger of always using 'latest' is that you run the risk of the build failing one day and not realising there has been a potentially big change in one of the prereqs.  (Is there a 'latest' link?)

ant 1.10.n is required because of its support for modularity.  The linux standard installs (apt-get ant etc.) install 1.9.x.

I see no reason not to move up to 1.10.2 but it would be wise to check the build still works before switching to using it in production.

1.10.1 is still available here: archive.apache.org/dist/ant/binaries/apache-ant-1.10.1-bin.zip

**Comment by karianna** [comment]
I think this can be closed now yes?

**Comment by Mesbah-Alam** [comment]
@karianna - not yet :)... Based on Simon's comment, we have decided to point to archive.apache.org/dist/ant/binaries/apache-ant-1.10.1-bin.zip instead of the latest, so that we can safely say that it will work with modularity tests (when they do become available in openj9)

**Comment by Mesbah-Alam** [comment]
@TianyuZuo - I asked you to review the following PR which reverts the change made previously to update Ant version to 1.10.2: https://github.com/AdoptOpenJDK/stf/pull/33. 
Once this goes in, I'll have another PR to update the Ant download url to archive.apache.org/dist/ant/binaries/apache-ant-1.10.1-bin.zip

**Comment by sxa** [comment]
@Mesbah-Alam Can you prepare the new PR so we can merge both simultaneously (or create an alternate PR that does the change to pick up 1.10.1 from the new location) as the current code will break on it's own and I wouldn't want to leave it in such a state

**Comment by Mesbah-Alam** [comment]
Created an alternative PR that includes reverting 1.10.2->1.10.1 plus the change to the Ant.zip Archive path: https://github.com/AdoptOpenJDK/stf/pull/34/files , @TianyuZuo @sxa555

**Comment by sxa** [comment]
Looks good - I did a diff with the version before the change was made and nothing controversial in there - will approve it :-)
