### ISSUE TITLE
Fix main page link to systemtest repo

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/stf#47]
Currently the link has is to openjdk-systemtests so is broken, as the repo name is openjdk-systemtest

I do not see that I have editing rights to make that change, so opened this issue.

**Comment by Mesbah-Alam** [comment]
Can you please post the name of the file in which you see this broken link?

**Comment by smlambert** [comment]
<img width="725" alt="screen shot 2018-11-12 at 7 08 37 pm" src="https://user-images.githubusercontent.com/2836948/48382316-82ebf580-e6ae-11e8-8ba7-d459427d7442.png">

**Comment by Mesbah-Alam** [comment]
It seems to be an introductory description of the stf repo itself. This line does not exist in any file inside the repo. Also, I do not see any option in the repo page to edit it. @lumpfish - could you please have a look?

**Comment by lumpfish** [comment]
This link describes how to change it: https://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github,, but the option 'Edit' is not there when I look at the repository.   The option is there on my fork of the repository, so I assume there some authorisation we don't have.  @karianna ?

**Comment by karianna** [comment]
Yep - Fixed!
