### ISSUE TITLE
Remove use of subst when on Cygwin

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/stf#49]
From version 1.7.0, for Cygwin, `PATH_MAX=4096`: https://cygwin.com/ml/cygwin-announce/2009-02/msg00018.html

Both Adopt as well as OpenJ9 machines use Cygwin 2.10.0 

@lumpfish  - Given the above, do we need to use `subst` to shorten Windows paths while on Cygwin?

**Comment by Mesbah-Alam** [comment]
@lumpfish can we edit the condition of the following if statement and add a check for Cygwin as well? 

https://github.com/AdoptOpenJDK/stf/blob/21a60ab0fecaf127142882aa37ffce1cf9438fa4/stf.core/scripts/stf.pl#L347

**Comment by Mesbah-Alam** [comment]
Originally added by this PR: https://github.com/AdoptOpenJDK/stf/pull/43#event-1699410541

**Comment by Mesbah-Alam** [comment]
Note: this use of subst is causing system tests to not run on openj9 builds.

**Comment by lumpfish** [comment]
The long filename issue is that some windows commands (eg. copy, rmdir) will not work with long path names longer than 260 chars (including slashes and drive).  The underlying file system supports longer file names so you can create files but then potentially not be able to run commands against them.

Typically the issues arise when there is a third party test suite which is unzipped beneath a certain root directory, such as a Jenkins workspace, which has a name long enough to exceed the 260 char lmit when the unzipped file path is added to it.

subst is the standard way to get round this issue (so subst t: jenkins_workspace means you can refer to those files as t:).

Changing the above code to say "if ($^O eq 'MSWin32') {  and not running on cygwin" will stop the subst being done.  Whether this affect test runs depends on the tests being invoked.  I think JCK and Eclipse test cases have caused problems in the past.

You will need to work out how to code "and not running on cygwin".  Perhaps there's an environment variable you can use, or maybe a command which will only work if running under cygwin?

**Comment by Mesbah-Alam** [comment]
Do we run or plan to run JCKs or Eclipse tests any more in the new builds?

**Comment by Mesbah-Alam** [comment]
Also thinking, can there be a case where the platform we are running on is not Cygwin but is MSWin32 ? I.e., if we decide to add the new condition, does it even make sense to have the subst code at all.

**Comment by lumpfish** [comment]
I can only say that the code is there because those issues have been encountered in the past.  If you remove the subst there is a chance they might reappear depending on what files are in or are created by the tests being run.  You could just comment the code out for now and see whether any tests currently being run suffer as a result.

**Comment by karianna** [comment]
> Do we run or plan to run JCKs or Eclipse tests any more in the new builds?

Not the JCK no.

**Comment by Mesbah-Alam** [comment]
@lumpfish - thanks for clarifying. I will go ahead and comment out the subst related code in stf.pl. Test shows that the system tests on Windows run normally with this change in internal Jenkins as well as openj9 jenkins. Will create new issue if the problem re-appears in future.
