### ISSUE TITLE
Discuss and agree correct way to detect OpenJ9 builds vs IBM builds

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/stf#7]
As a tactical "quick fix" I put in https://github.com/AdoptOpenJDK/stf/pull/5 to address https://github.com/eclipse/openj9-systemtest/issues/2 where the OpenJ9 version strings were not being detected as the methods were designed to assume that J9 == IBM Java - the fix involved modifying `isIBMJvm()` in JavaVersion.java to allow `OpenJ9` in the version string as well as `IBM` to give a `true` return value to `isIBMJvm()`. This is bending the truth a little so we should decide whether to change it to something like `isJ9VM()` or, if required, split it into separate `isJ9VM()` (or `isOpenJ9VM()`) and `isIBMJvm()` methods

**Comment by lumpfish** [comment]
The use case is to detect whether or not certain capabilities are available - e.g. to fire a signal at the JVM to get a core dump if a process is hung, so OpenJ9 and IBM Java are currently synonymous.  However, maybe that will change.
So isIBMJvm (definitely IBM Java), isOpenJ9Jvm (definitely OpenJ9) and isJ9Jvm (either IBM Java or OpenJ9) would appear to cover all the options.  The test implementer could then use what they need.  There will be a number of isIBMJvm() calls to change to isJ9Jvm().

**Comment by lumpfish** [comment]
AdoptOpenJDK openjdk-openj9 builds are currently not being detected as using a J9 VM because stf.load has an isIBM method with the check:
```
	String jvmVendor = System.getProperty("java.vm.vendor");
    	if (jvmVendor != null && jvmVendor.contains("IBM")) {
```
java.vm.vendor contains "Eclipse OpenJ9" in AdoptOpenJDK openjdk-openj9 builds.

**Comment by lumpfish** [comment]
Fixed the not taking dumps issue in https://github.com/AdoptOpenJDK/stf/pull/46
