### ISSUE TITLE
STF check_free_space() needs option to be disabled for dynamic filesystem environments

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/stf#79]
For dynamic filesystems, like zfs, mounts are growable, thus querying current free disk space is not valid, as it will simply grow... In these environments we need an option to disable the STF check_free_space() method:
https://github.com/AdoptOpenJDK/stf/blob/7c246920983f76adae8595b1d4f9677b956e08c2/stf.core/scripts/stf.pl#L379

**Comment by jdekonin** [comment]
I think the check and output to detail how much would still be a valid bit of information to leave in though.  Just not the "fail if not enough is free" part.

**Comment by Mesbah-Alam** [comment]
Does it make sense to altogether remove the step to `exit` if `$mb_free < 3072` on all platforms? Or is it still useful to exit on platforms where the filesystem is not growable? (In that case we'd need the list of such platforms).

**Comment by andrew-m-leonard** [comment]
So at the moment I only know of ZFS on zOS, and only when it has been configured with AGGRGROW

**Comment by Mesbah-Alam** [comment]
In that case, it makes sense to update the logic in stf.pl to only exit due to `$mb_free < 3072` when not on z/OS. I'll have a PR for that.
