### ISSUE TITLE
Build failure if PREREQS_ROOT contains multiple paths

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/stf#87]
During the STF build (`make configure`) prereqs (e.g. junit, asm, windows-sysinternals) are installed to the PREREQS_ROOT make macro location.  This is then passed as a command line argument into stf itself which it uses to add the correct classpath values to the various test command lines.

STF supports multiple paths (separated by the `;` path separator on all platforms), which allows for prereqs used only by one or two tests (e.g. the JCK) to be placed in a different directory to those installed by the STF `make configure` build step.

However, when multiple paths are specified in this way the `make build` step fails because the prereq validation treats the multiple paths as a single path.  The build outputs error messages similar to:
```
print-log4j-2.13.3-error:
     [echo] ERROR: Cannot find log4j-api-2.13.3 at C:\systemtest_prereqs;c:\jck\log4j-2.13.3\log4j-api-2.13.3.jar and / or log4j-core-2.13.3 at C:\systemtest_prereqs;c:\jck\log4j-2.13.3\log4j-core-2.13.3.jar
```
Note in this case the extra `c:\jck` which was added to the build PREREQS_ROOT macro.

Since the STF `make configure` step checks that only a single PREREQS_ROOT path has been specified (if not the build fails with `makefile:173: *** ERROR: Only one PREREQS_ROOT directory can be specified for make configure.  Stop.`) then a fix would be to assume that the `make configure` prereqs have been installed to the first path in PREREQS_ROOT and use that for validating that those prereqs exist.

**Comment by lumpfish** [comment]
PRs to fix:
stf - https://github.com/AdoptOpenJDK/stf/pull/88
openjdk-systemtest - https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/371

**Comment by Mesbah-Alam** [comment]
@lumpfish - Could we please run some grinders to ensure the changes made in the above 2 PRs would not break the TKG way of running STF based tests?

**Comment by lumpfish** [comment]
There are already links to test runs in the PRs
stf - #88
openjdk-systemtest - AdoptOpenJDK/openjdk-systemtest#371
The tests were run with the changes from both PRs
