### ISSUE TITLE
Support running tests against java builds with no bin/java.exe

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/stf#9]
The AdoptOpenjdk java 8 builds do not have a bin/java(.exe) file, they only have a jre/bin/java(.exe) file.
STF requires that JAVA_HOME points to the directory above the /bin containing java(.exe).  If that is set to /jre it is OK for most tests, but tests which need access to tools such as javac, javah or jar cannot then locate them via JAVA_HOME.

**Comment by lumpfish** [comment]
The latest AdoptOpenJDK java 8 builds do have a bin/java.exe file, so this doesn't need to be done unless we encounter any other jre builds with no bin/java.exe in future.

**Comment by gdams** [comment]
@lumpfish yeah that shouldn't have been happening.... Have you got a copy of the Binary that didn't have `bin/java.exe`?

**Comment by lumpfish** [comment]
I had deleted the old binary I was using when I got the latest version.  I've re downloaded it from the AdtopOpenJDK download site, but the bin/java.exe is there.  I can only assume I had accidentally deleted the java.exe on my local machine.
