### ISSUE TITLE
download-file macro fails intermittently on Windows with Unable to establish SSL connection

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/stf#96]
**Overview:**

On some internal Windows machines, we are seeing the `wget` command that downloads `SysinternalsSuite.zip` file failing with following error: 

```
00:10:31.726  configure-windows-sysinternals:
00:10:31.726       [echo] Executing macro download-file
00:10:31.726       [echo] File to download: https://download.sysinternals.com/files/SysinternalsSuite.zip
00:10:31.726       [echo] Destination: C:\temp\/windows_sysinternals/SysinternalsSuite.zip
00:10:31.726       [echo] Download tool: wget
00:10:31.726       [exec] --2020-12-14 22:45:39--  https://download.sysinternals.com/files/SysinternalsSuite.zip
00:10:31.726       [exec] Resolving download.sysinternals.com (download.sysinternals.com)... 152.199.4.33
00:10:31.726       [exec] Connecting to download.sysinternals.com (download.sysinternals.com)|152.199.4.33|:443... connected.
00:10:31.726       [exec] GnuTLS: The request is invalid.
00:10:31.726       [exec] Unable to establish SSL connection.
00:10:31.726       [exec] Result: 4
00:10:31.726      [unzip] Expanding: C:\temp\windows_sysinternals\SysinternalsSuite.zip into C:\Users\jenkins\workspace\Test_openjdk8_j9_special.system_x86-64_windows_xl_Nightly_testList_4\openjdk-tests\systemtest_prereqs\windows_sysinternals

```

**Observations:** 

1) The issue goes away (on the same Windows machine), if we use `--secure-protocol=TLSv1` instead of `--no-check-certificate` in the wget option. (e.g https://github.com/AdoptOpenJDK/stf/compare/master...Mesbah-Alam:fix-sysinternals-bug?expand=1) (Details in internal backlog/issues/427). 

2) However, Fix in (1) breaks the [systemtest.getDependency](https://ci.adoptopenjdk.net/job/systemtest.getDependency/126/console) build: with `OpenSSL: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version` error. So, apparently not all third party websites supports TSLv1. The solution has to take this into account.

3) Wget version on the failing (internal) machine: `wget-1.19.1`. Wget version listed in system test requirement is [1.11.4-1-bin.zip](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.build/docs/build.md). 

**Summary:**

We can not use  `--no-check-certificate` in the [download-file macro](https://github.com/AdoptOpenJDK/stf/blob/master/stf.build/include/top.xml#L419) for all prereq downloads. Some, especially, SysinternalsSuite.zip is requiring (at least on some machines, e.g. some wget versions) to use `--secure-protocol=TLSv1`. But, we can not use `--secure-protocol=TLSv1` for all prereq downloads either. 

@lumpfish @llxia

**Comment by lumpfish** [comment]
Note that the STF build just uses the wget / curl which is on PATH.
I recently set up a machine locally to run STF tests and found that wget-1.20.3 worked for me.

**Comment by Mesbah-Alam** [comment]
Additional note: the internal machine, on which we do not see the above issue and download-file works as is, has the exact same version of Wget as that on the machine where it fails: `wget-1.19.1`.

**Comment by sxa** [comment]
@willsparker is there any chance this is related to the change you saw recently in the defaults on WIndows Vagrant VMs? https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1858? If @Mesbah-Alam 's is definitely the cygwin one then it's unlikely but worth some consideration especially since it seems sensitive to the TLS version.

**Comment by Willsparker** [comment]
It looks to be the same issue- however, for me, this was only affecting `Powershell` 's `Invoke-WebRequest` (which is aliased to `wget`) - `Cygwin`'s `wget` worked fine at least in my testing.

**Comment by Mesbah-Alam** [comment]
The download-file macro (https://github.com/adoptium/STF/blob/master/stf.build/include/top.xml#L370) now uses curl.
